[tool.poetry]
name = "liboqs-pwr"
version = "0.12.0"
description = "Python bindings for liboqs, providing post-quantum public key cryptography algorithms"
readme = "README.md"
license = "MIT"
authors = ["Open Quantum Safe project <contact@openquantumsafe.org>"]
packages = [{ include = "oqs" }]
keywords = ["liboqs", "post-quantum", "cryptography", "oqs", "security"]
repository = "https://github.com/keep-pwr-strong/liboqs-python"
documentation = "https://docs.openquantumsafe.org/"

[tool.poetry.dependencies]
python = ">=3.9"
requests = "^2.32.3"
cryptography = "^44.0.2"
mypy = "^1.14.1"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.2"
ruff = "^0.9.4"
isort = "^5.13.2"
pre-commit = "^4.1.0"
nose2 = "^0.15.1"
types-pytz = "^2024.2.0.20241221"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
