[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "promptgraphtools"
version = "0.1.32"
authors = [
  { name = "Tucker Weed", email = "tuckerweed@gmail.com" }
]
description = "A lightweight, highly concurrent execution graph framework."
readme = "README.md"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
license = { file = "LICENSE" }
dependencies = [
    "jinja2",
    "google-genai==0.2.2",
]

[project.urls]
Homepage = "https://github.com/tucker-weed/prompt-graph-tools"

[project.scripts]
promptgraph = "promptgraphtools.__main__:main" 
