[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "packify"
version = "0.3.1"
authors = [
  { name="k98kurz", email="k98kurz@gmail.com" },
]
description = "Serialize and deserialize almost anything easily."
readme = "readme.md"
requires-python = ">=3.9"
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: ISC License (ISCL)",
  "Operating System :: OS Independent",
  "Topic :: Software Development :: Libraries",
]

[project.urls]
"Homepage" = "https://github.com/k98kurz/packify"
"Bug Tracker" = "https://github.com/k98kurz/packify/issues"