[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "telegram-bot-utils"
version = "0.0.4"
description = "Engine for web3 smart contracts automatization."
authors = [
    {name = "Indeoo", email = "indeooars@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
dependencies = [
    "alembic==1.14.0",
    "asyncpg==0.30.0",
    "python-telegram-bot==21.7"
]

[project.urls]
Homepage = "https://github.com/Indeoo/market-analyzer/"

[tool.setuptools]
py-modules = ["telegram_bot_utils"]

[tool.setuptools.packages.find]
include = ["telegram_bot_utils*"]

[tool.setuptools.package-data]
"telegram_bot_utils" = ["resources/**/*"]
