[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "creduse"
dynamic = ["version"]
description = "Python SDK for Creduse"
readme = "README.md"
requires-python = ">=3.13"
license = {text="MIT License"}
authors = [{name="Creduse", email="support@creduse.com"}]
dependencies = [
    "hatch>=1.14.0",
    "httpx>=0.28.1",
    "pydantic>=2.10.6",
]

[tool.hatch.version]
path = "__version__.py"


[tool.hatch.build.targets.wheel]
packages = ["."]

[dependency-groups]
dev = [
    "ruff>=0.9.4",
    "pytest>=8.3.4",
    "python-dotenv>=1.0.1",
    "pytest-mock>=3.14.0",
    "ipykernel>=6.29.5",
    "pytest-asyncio>=0.25.3",
]

