[tool.poetry]
name = "mpcorbfile"
version = "0.3.2"
description = "Read and write MPCORB files from  minor planet center"
readme = "README.rst"
license = "MIT"
authors = ["nachoplus <mas.ignacio@gemail.com>"]
maintainers = ["nachoplus <mas.ignacio@gemail.com>"]
repository = "https://github.com/nachoplus/mpcorbfile"
#bugs = "https://github.com/nachoplus/mpcorbfile/issues"
#changelog = "https://github.com/nachoplus/mpcorbfile/blob/master/changelog.md"
homepage = "https://github.com/nachoplus/mpcorbfile"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Web Environment",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Astronomy",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Environment :: Console",
    "Programming Language :: Python :: 3 :: Only",
]
packages = [
    { include = "mpcorbfile", from="src"}
  ]

[tool.poetry.scripts]
mpcorbfile = 'mpcorbfile.cli:mpcorbfilecli'

[tool.poetry.dependencies]
python=">=3.10"
click = "^8.1.8"
numpy = "^2.2.3"

[tool.poetry.group.dev.dependencies]
black = "*"
mypy = "*"
pre-commit = "*"
ruff = "*"
pandas = "^2.2.3"
tox = "^4.24.1"
ipykernel = "^6.29.5"

[tool.poetry.group.test.dependencies]
coverage = "*"
pytest = "*"
tox = "*"

[tool.poetry.extras]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
