[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "emojito-py"
version = "0.1.1"
description = "Encode text into emojis using Unicode steganography"
authors = [
  { name = "Matija OsreÄki", email = "python@matijao.com" },
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.7"
keywords = ["emoji", "steganography", "encoding", "unicode"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.scripts]
emojito = "emojito.cli:main"

[project.urls]
"Homepage" = "https://github.com/matijaoe/emojito"
"Bug Tracker" = "https://github.com/matijaoe/emojito/issues"
"Repository" = "https://github.com/matijaoe/emojito.git"

[tool.hatch.envs.default]
publish-target = "github"

[tool.hatch.publish.targets.github]
repository = "https://github.com/matijaoe/emojito"

[tool.hatch.build.targets.wheel]
packages = ["emojito"]
