[tool.poetry]
name = "compass.virtuals_sdk"
version = "0.1.76"
description = ""
authors = ["royalnine <17271567+royalnine@users.noreply.github.com>"]
readme = "README.md"
packages = [
  { include = "compass"}
]

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
"compass.api_client" = "*"
game-sdk = "^0.1.3"
python-dotenv = "^1.0.1"
web3 = "^7.7.0"

[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
isort = "^6.0.0"
docformatter = "^1.7.5"
ruff = "^0.9.7"

