[package]
name = "murasame-pp-py"
version = "1.0.1"
description = "osu! difficulty and pp calculation for all modes"
authors = ["Max Ohn <ohn.m@hotmail.de>", "tsunyoku <tsunyoku@gmail.com>", "namakemono-san <contact@nmkmn.moe>"]
license = "MIT"
edition = "2021"

[lib]
name = "murasame_pp_py"
crate-type = ["cdylib"]

[dependencies]
murasame-pp = { git = "https://github.com/murasameosu/murasame-pp-rs", rev = "60eb83199a2d3d27566e92f8adfff45e40f6cf8a" }
pyo3 = { version = "0.17", features = ["extension-module","macros"] }


[profile.release]
lto = "fat"
codegen-units = 1
strip = "debuginfo"
