[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "STmulator"
version = "0.1.2"
description = "3D Spatial Transcriptomics Simulator, with realistic varaince modeling and statiscial fitting. Here is a early preview version."
readme = "README.md"
authors = [
    {name = "Yiru CHEN", email = "yiru.22@intl.zju.edu.cn"}
]
license = {text = "MIT"}
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "alphashape>=1.3.1",
    "anndata>=0.11.3",
    "geomloss>=0.2.6",
    "joblib>=1.1.0",
    "matplotlib>=3.7.3",
    "numba>=0.60.0",
    "numpy>=1.23.1",
    "pandas>=1.5.3",
    "paste2>=1.0.1",
    "scanpy>=1.11.0",
    "scikit-learn>=1.2.1",  
    "scipy>=1.7.3",
    "seaborn>=0.13.2",
    "Shapely>=2.0.7",  
    "torch>=1.12.1",
    "tqdm>=4.64.0",
]

[project.urls]
Homepage = "https://github.com/maiziezhoulab/SimulaTor"
Repository = "https://github.com/maiziezhoulab/SimulaTor"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]