[tool.poetry]
name = "django-nominopolitan"
version = "0.1.8"
description = "Neapolitan with namespaces - Django CRUD views"
authors = ["doctor-cornelius"]
readme = "README.md"
packages = [{include = "nominopolitan"}]
repository = "https://github.com/doctor-cornelius/django-nominopolitan"
homepage = "https://github.com/doctor-cornelius/django-nominopolitan"

[tool.poetry.dependencies]
python = "^3.12.3"
django = "^5.1.3"
django-htmx = "^1.21.0"
django-template-partials = "^24.4"

[tool.poetry.group.dev.dependencies]
neapolitan = "^24.8" # users of the package need to install it themselves
commitizen = "^3"
ipykernel = "^6"
pytest = "^8.2.1"
coverage = "^7"
pytest-mock = "^3.14.0"
pydantic = "^2.7.1"
validators = "^0.28.3"
django-crispy-forms = "^2.3"
crispy-bootstrap5 = "^2024.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

