[tool.poetry]
name = "tidle"
version = "1.0.7"
description = "tidle, the idle game."
authors = ["Kokonico <kokonico@duck.com>"]
scripts = { "tidle" = "tidle.cli:main"}
readme = "README.md"
dependencies = {"python" = "^3.8"}


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
