[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "python-builder"
version = "0.3.0"
description = "Implementation of generic python builder"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "pre-commit>=4.1.0",
    "pydantic>=2.10.6",
    "pytest>=8.3.3",
    "ruff>=0.9.9",
]

[tool.setuptools.packages.find]
where = ["src"]
