[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "llmcodxtracter"
version = "0.2.4"
description = "A Python library for extracting code snippets using LLMs"
readme = "README.md"
authors = [{ name = "Mohammed Muzammil Inamdar", email = "muzammil.inamdar98@gmail.com" }]
license = { text = "MIT" }
requires-python = ">=3.7"
dependencies = [
    "openai",  # Example dependency, remove if not needed
]

[tool.setuptools]
package-dir = {"" = "src"}

[project.urls]
"Homepage" = "https://github.com/DarthMuzammil/llmcodxtracter"
"Repository" = "https://github.com/DarthMuzammil/llmcodxtracter"
